### PR TITLE
Use sudo when querying post-operation status.

### LINKED ISSUE #194: "open /var/lib/gravity/local/gravity.db: permission denied" after upgrade when system_uid/system_gid are set
When `system_uid` and `system_gid` are set to non-standard values, robotest upgrade tests will fail to gather status after the upgrade with " open /var/lib/gravity/local/gravity.db: permission denied"

### Context
As part of #193 testing I ran the following test case:

[logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-26T16:34:51.801000000Z&customFacets=&limitCustomFacetWidth=true&interval=CUSTOM&scrollTimestamp=2020-03-26T00:51:25.420127587Z&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2225b8c851-a881-428f-9325-3e42399942bd%22%0Alabels.__suite__%3D%22350907b0-48ce-4810-98a0-b650f358d5ff%22&dateRangeEnd=2020-03-26T16:34:48.210Z&dateRangeUnbound=backwardInTime)

In it, robotest fails to gather logs after a successful upgrade from 5.5.28 to 5.5.38 with following record:

```
[
 {
   "insertId": "1qg0vryg1hw2xx9",
   "jsonPayload": {
     "name": "walt-upgrade3lts-1",
     "ip": "10.138.0.42",
     "public_ip": "35.247.111.67",
     "cmd": "cd /home/centos/upgrade && ./gravity status --operation-id=1b110263-2cbf-46cf-b937-74e6b7035225 -q",
     "logs": "https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2225b8c851-a881-428f-9325-3e42399942bd%22%0Alabels.__suite__%3D%22350907b0-48ce-4810-98a0-b650f358d5ff%22%0Aseverity%3E%3DINFO&authuser=1&expandAll=false&project=kubeadm-167321",
     "stream": "stdout",
     "message": "\u001b[31m[ERROR]: open /var/lib/gravity/local/gravity.db: permission denied\r\n\u001b[0m",
     "stack": [
       "/lib/ssh/run_parse.go:198",
       "/lib/ssh/run_parse.go:167"
     ]
   },
   "resource": {
     "type": "project",
     "labels": {
       "project_id": "kubeadm-167321"
     }
   },
   "timestamp": "2020-03-26T00:45:24.259941547Z",
   "severity": "DEBUG",
   "labels": {
     "__suite__": "350907b0-48ce-4810-98a0-b650f358d5ff",
     "__name__": "walt-upgrade3lts-1",
     "__uuid__": "25b8c851-a881-428f-9325-3e42399942bd",
     "__param__": "{\"role\":\"node\",\"cluster\":\"\",\"flavor\":\"one\",\"remote_support\":false,\"state_dir\":\"/var/lib/gravity\",\"os\":{\"Vendor\":\"centos\",\"Version\":\"7\"},\"storage_driver\":\"overlay2\",\"service_uid\":994,\"service_gid\":994,\"nodes\":1,\"script\":null,\"from\":\"s3://hub.gravitational.io/gravity/oss/app/telekube/5.5.28/linux/x86_64/telekube-5.5.28-linux-x86_64.tar\"}"
   },
   "logName": "projects/kubeadm-167321/logs/TestMain%2Frun%2Fwalt-upgrade3lts-1",
   "receiveTimestamp": "2020-03-26T00:45:25.301026695Z"
 }
]
```

After discussing with @r0mant this is because centos has a default UID:GID of 1000:1000 with allows `./gravity status` to work in runs without uid/git munging.  However, when uid/gid are set (or all the time), this command should be run with sudo, as our other gravity status commands are. Compare:

https://github.com/gravitational/robotest/blob/cd3f125808c8869f73cc5668446b240302cc26b4/infra/gravity/node_commands.go#L592
vs 
https://github.com/gravitational/robotest/blob/cd3f125808c8869f73cc5668446b240302cc26b4/infra/gravity/node_commands.go#L311-L312

### PR DESCRIPTION
**Pull request by wadells**
Older version of gravity try to read `/var/lib/gravity/local/gravity.db`
with the current user.  When these files are owned by someone other than
the current user (i.e. the system_uid/system_gid parameters are set)
`gravity status` will always fail with:

  open /var/lib/gravity/local/gravity.db: permission denied

We avoid these permission problems by using sudo to run gravity (which
is consistent with all other executions of gravity in node_commands.go).

Fixes #194.

### Testing Done
Before this change: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-26T23:27:47.848000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-03-26T22:28:13.863Z&interval=PT1H&scrollTimestamp=2020-03-26T23:26:59.342140371Z&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22eeee4fc2-9030-4496-8431-79c3dcb2d5f9%22%0Alabels.__suite__%3D%22dacbcbe5-acce-40e8-b48a-45588beb350b%22%0Aseverity%3E%3DINFO&dateRangeEnd=2020-03-26T23:28:13.863Z)
After this change: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-26T23:27:47.848000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-03-26T22:28:13.863Z&interval=PT1H&scrollTimestamp=2020-03-26T23:26:59.342140371Z&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22eeee4fc2-9030-4496-8431-79c3dcb2d5f9%22%0Alabels.__suite__%3D%22dacbcbe5-acce-40e8-b48a-45588beb350b%22%0Aseverity%3E%3DINFO&dateRangeEnd=2020-03-26T23:28:13.863Z)

### CODE REVIEW

File: infra/gravity/node_commands.go [hunk 1]
```diff
@@ -568,11 +568,10 @@ const (
 // runOp launches specific command and waits for operation to complete, ignoring transient errors
 func (g *gravity) runOp(ctx context.Context, command string, env map[string]string) error {
 	var code string
-	executablePath := filepath.Join(g.installDir, "gravity")
+	sudoGravity := fmt.Sprintf(`cd %v && sudo -E ./gravity`, g.installDir)
```
Comment (wadells) [inline infra/gravity/node_commands.go]: I find this `cd {{ .installDir }} && sudo ./gravity` pattern a bit odd, but it is consistent with what is in most of the rest of node_commands.go.

Some totally ad-hoc stats:

```
walt@work:~/git/robotest$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'grav/master'.
walt@work:~/git/robotest$ grep -c 'filepath.Join(g.installDir, "gravity")' infra/gravity/node_commands.go
2
walt@work:~/git/robotest$ grep -c 'cd .* && .* \./gravity' infra/gravity/node_commands.go                
6
```

I considered unifying these to use a common code path, as there tends to be a bit of drift between different invocations (e.g. a missing `sudo` here, `-E` in some places) that is likely cause for future inconsistencies/bugs along the lines of #194.  However that greatly increased the scope of this PR.  I'd be glad to revisit if y'all think it is worthwhile.
