### PR TITLE
Properly parse Gravity 5.0.36 status

### LINKED ISSUE #247: cannot unmarshal string into Go struct field ClusterStatus.system_status of type int
## Summary

When testing Robotest 2.0.0 against Gravity 5.5 ([logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-06-09T18:19:49.571000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22c4de5ddd-4a8e-473e-9366-4e55d6744149%22%0Alabels.__suite__%3D%22da91d3b1-a8be-4394-a166-4dd1b851f913%22%0Aseverity%3E%3DINFO&dateRangeEnd=2020-06-09T18:19:46.952Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-06-09T02:00:24.572936433Z)), WaitForActiveStatus failed with:

```
ERROR REPORT:
Original Error: *json.UnmarshalTypeError json: cannot unmarshal string into Go struct field ClusterStatus.system_status of type int
Stack Trace:
	/go/src/github.com/gravitational/robotest/infra/gravity/parse.go:19 github.com/gravitational/robotest/infra/gravity.parseStatus.func1
	/go/src/github.com/gravitational/robotest/lib/ssh/run_parse.go:103 github.com/gravitational/robotest/lib/ssh.RunAndParse.func1
	/go/src/runtime/asm_amd64.s:1337 runtime.goexit
```

Looks like we'll need a case statement for 5.5.

### PR DESCRIPTION
**Pull request by wadells**
## Description
This PR fixes a Gravity 5.0.x compatiblity regression introduced by https://github.com/gravitational/robotest/pull/233.  Specifically, when trying to parse the output of `gravity status --output=json` on 5.0.36 robotest would fail with the following error: `json: cannot unmarshal string into Go struct field`.

### Risk Profile
 - Bug fix (patch release)

### Related Issues
Fixes #247.

## Testing Done
See the unit tests added.  Here is what it looks like to run them:

<details><summary><code>go test ./infra/gravity</code> before the second commit</summary>

```
walt@work:~/git/robotest$ go test ./infra/gravity/
--- FAIL: TestGravity5036ActiveStatusValidation (0.00s)
    gravity_test.go:127: 
                Error Trace:    gravity_test.go:127
                Error:          Received unexpected error:
                                json: cannot unmarshal string into Go struct field ClusterStatus.cluster.system_status of type int
                Test:           TestGravity5036ActiveStatusValidation
    gravity_test.go:130: 
                Error Trace:    gravity_test.go:130
                Error:          Received unexpected error:
                                expected system_status 1, found 0
                Test:           TestGravity5036ActiveStatusValidation
--- FAIL: TestGravity5036DegradedStatusValidation (0.00s)
    gravity_test.go:147: 
                Error Trace:    gravity_test.go:147
                Error:          Received unexpected error:
                                json: cannot unmarshal string into Go struct field ClusterStatus.cluster.system_status of type int
                Test:           TestGravity5036DegradedStatusValidation
FAIL
FAIL    github.com/gravitational/robotest/infra/gravity 0.013s
FAIL
```
</details>

<details><summary><code>go test ./infra/gravity</code> after</summary>

```
walt@work:~/git/robotest$ go test ./infra/gravity/
ok      github.com/gravitational/robotest/infra/gravity (cached)
```
</details>

Here is a complete 5.0.36 install: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-08-19T00:46:32.173000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%226a9aebd1-5e5d-4879-9cc2-2db5601f15cf%22%0Alabels.__suite__%3D%22f999ec85-c9f0-4ab2-be37-96c59d48183a%22%0Aseverity%3E%3DINFO&dateRangeStart=2020-08-18T23:46:33.411Z&dateRangeEnd=2020-08-19T00:46:33.411Z&interval=PT1H&scrollTimestamp=2020-08-19T00:42:13.093385539Z)

## Additional Information
I considered splitting the datamodel, such that GravityStatus became an interface fufilled by two different implementations: `Gravity50ClusterStatus` and `Gravity52ClusterStatus` (or the like).  I chose not to go with this approach because:
* It is more invasive. It required rewriting every signature and piece of code that consumes `GravityStatus` or any of its member fields.
* The life expectancy of this code is not that long. 5.0.x has been out of support for over a year (EoS April 13, 2019), and at some point we'll stop testing `--upgrade-via` tests from this release whereupon all this code can be removed wholesale.

### CODE REVIEW

File: infra/gravity/node_commands.go [hunk 1]
```diff
@@ -155,14 +155,79 @@ type ClusterStatus struct {
 	Cluster string `json:"domain"`
 	// State is the cluster state
 	State string `json:"state"`
-	// SystemStatus is the cluster status, see https://github.com/gravitational/satellite/blob/7.1.0/agent/proto/agentpb/agent.proto#L50-L54
-	SystemStatus int `json:"system_status"`
+	// SystemStatus is the cluster status, custom unmarshalling logic needed to accommodate Gravity differences
+	SystemStatus int
```
Comment (r0mant) [inline infra/gravity/node_commands.go:159]: Shouldn't then this be explicitly excluded from marshal/unmarshal?

```go
SystemStatus int `json:"-"`
```

File: infra/gravity/node_commands.go [hunk 2]
```diff
@@ -155,14 +155,79 @@ type ClusterStatus struct {
...
 }
 
+// unmarshalSystemStatus is a helper type to parse string or integer system statuses.
+//
+// For the original definitions and mappings see:
+//   https://github.com/gravitational/satellite/blob/5.0.2/agent/proto/agentpb/agent.proto#L36-L40
+//   https://github.com/gravitational/satellite/blob/5.0.2/agent/proto/agentpb/agent.pb.go#L48-L63
+func unmarshalSystemStatus(val json.RawMessage, status *int) error {
+	err := json.Unmarshal(val, &status)
+	if err != nil { // parsing as int failed, try parsing as a string and converting
```
Comment (r0mant) [inline infra/gravity/node_commands.go:173]: In cases like this I would invert the condition to keep most of the code left-indented, it's a bit cleaner.

```go
err := json.Unmarshal(val, &status)
if err == nil {
  return nil
}
// rest of the code
```

File: infra/gravity/node_commands.go [hunk 3]
```diff
@@ -155,14 +155,79 @@ type ClusterStatus struct {
...
+		if err2 := json.Unmarshal(val, &str); err2 != nil {
+			return trace.BadParameter("unable to parse system_status %q as int or string: %v, %v", val, err, err2)
+		}
+		switch str {
+		case "running":
+			*status = constants.SystemStatus_Running
+		case "degraded":
+			*status = constants.SystemStatus_Degraded
+		default:
+			return trace.BadParameter("unknown system_status: %q", str)
```
Comment (r0mant) [inline infra/gravity/node_commands.go:184]: Should this rather fallback to `*status = constants.SystemStatus_Unknown` or something like this instead of failing the entire marshaling?

File: infra/gravity/node_commands.go (hunk 1 above)
Comment (wadells) [reply infra/gravity/node_commands.go]: Good catch.  Fixed in bc97e32.

File: infra/gravity/node_commands.go (hunk 2 above)
Comment (wadells) [reply infra/gravity/node_commands.go]: Addressed in a0af55e.

File: infra/gravity/node_commands.go (hunk 3 above)
Comment (wadells) [reply infra/gravity/node_commands.go]: I spent some time exploring this.  Outcome-wise, it doesn't matter much either way.  Both implementations will fail after a 5 minute timeout.  One with the above BadParameter parse error and the other with the following error:

https://github.com/gravitational/robotest/blob/400f3eb5912f3647df1f29b027d89bedcf7cbbda/infra/gravity/cluster_status.go#L43

I think I prefer the BadParamerter parse error for two reasons:

1) converting string -> int is lossy.  The original string is more useful/indicative of the problem than the int `0` (or any int)
2) Keeping status parse errors distinct from "parseable but unhealthy" is useful for #181 -- one of my longer term goals for the code base.  Admittedly we don't make a distinction currently:

https://github.com/gravitational/robotest/blob/400f3eb5912f3647df1f29b027d89bedcf7cbbda/infra/gravity/cluster_status.go#L70-L83

But as part of this investigation I've got a patch in the works to make that distinction and fail fast on non-retryable failures during status collection.
