### PR TITLE
Fix log links when run from GCP nodes & opportunistic cleanups

### LINKED ISSUE #265: Robotest log links are broken when run from a GCP instance
When robotest is run from a GCE vm (either directly, or inside a container), the log links are invalid.  For example:

https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2200504005-bb18-4d00-8481-73e731f229e2%22%0Alabels.__suite__%3D%22c8ccee0b-f2cc-499f-9d37-fded185b5b49%22%0Aseverity%3E%3DINFO&authuser=1&expandAll=false&project=kubeadm-167321

Removing `resource.type="project"` from the query string results in logs that resolve:

https://console.cloud.google.com/logs/viewer?advancedFilter=labels.__uuid__%3D%2200504005-bb18-4d00-8481-73e731f229e2%22%0Alabels.__suite__%3D%22c8ccee0b-f2cc-499f-9d37-fded185b5b49%22%0Aseverity%3E%3DINFO&authuser=0&expandAll=false&project=kubeadm-167321

The cause is documented here:

https://pkg.go.dev/cloud.google.com/go/logging?tab=doc#hdr-Viewing_Logs

Google cloud's logging implicitly marks logs from submitted from instances:

```
resource: {
  type: "gce_instance"
  labels: {
    project_id: "<project>"
    instance_id: "<instance>"
    zone: "<zone>"
  }
}
```

vs logs submitted from elsewhere:

```
resource: {
  type: "project"
  labels: {
    project_id: "<project>"
  }
}
```

### PR DESCRIPTION
**Pull request by wadells**
## Description
This PR includes a logging fix when the robotest container is running from a GCP node, plus some test case refactoring I did along the route to diagnosing and understanding the issue.

### Risk Profile
 - Bug fix (patch release)

### Related Issues
Fixes #265 

## Testing Done
I published robotest-suite:2.2.0-alpha.0.6-5f438094 and used that from an upcoming gravity branch on a gcp instance:
<details><summary><code>make -C build.assets/robotest run</code></summary>

```
walt@gcp:~/git/gravity$ make -C build.assets/robotest run                                                                                                                                     
make: Entering directory '/home/walt/git/gravity/build.assets/robotest'
make -j /home/walt/git/gravity/build/current/robotest/images/robotest-7.0.7.tar /home/walt/git/gravity/build/current/robotest/images/robotest-7.0.13.tar /home/walt/git/gravity/build/current/robotest/images/robotest-7.0.12.tar /home/walt/git/gravity/build/current/robotest/images/robotest-7.0.16.tar
make[1]: Entering directory '/home/walt/git/gravity/build.assets/robotest'
make[1]: '/home/walt/git/gravity/build/current/robotest/images/robotest-7.0.7.tar' is up to date.
make[1]: '/home/walt/git/gravity/build/current/robotest/images/robotest-7.0.13.tar' is up to date.                                                                                            
make[1]: '/home/walt/git/gravity/build/current/robotest/images/robotest-7.0.12.tar' is up to date.
make[1]: '/home/walt/git/gravity/build/current/robotest/images/robotest-7.0.16.tar' is up to date.
make[1]: Leaving directory '/home/walt/git/gravity/build.assets/robotest'                                                                                                                     
bash run.sh /home/walt/git/gravity/build.assets/robotest/pr_config.sh
// snip sensitive credentials
level=info msg=RUNNING commit=5f438094bc7b11af0f92655c5118f28be89bd808 logs="https://console.cloud.google.com/logs/viewer?advancedFilter=severity%3E%3DINFO%0Alabels.__uuid__%3D%22c4e8fb75-abb9-4e13-b5de-f70723b13435%22%0Alabels.__suite__%3D%22ea4b678e-1162-4e59-8ba7-d874bd53ea71%22&authuser=1&expandAll=false&project=kubeadm-167321" name=ed56b800-install-1 param="{\"role\":\"node\",\"cluster\":\"\",\"flavor\":\"three\",\"remote_support\":false,\"state_dir\":\"/var/lib/gravity\",\"os\":{\"Vendor\":\"centos\",\"Version\":\"7\"},\"storage_driver\":\"overlay2\",\"installer_url\":\"/installer/robotest-current.tar\",\"nodes\":3,\"script\":null}" version=2.2.0-alpha.0.6+5f438094 where="[/cenkalti/backof/retry.go:37]"
```
</details>

Here is the link from the run:

https://console.cloud.google.com/logs/viewer?advancedFilter=severity%3E%3DINFO%0Alabels.__uuid__%3D%22c4e8fb75-abb9-4e13-b5de-f70723b13435%22%0Alabels.__suite__%3D%22ea4b678e-1162-4e59-8ba7-d874bd53ea71%22&authuser=1&expandAll=false&project=kubeadm-167321

And a link from a run from my personal laptop (non-gcp):

https://console.cloud.google.com/logs/viewer?advancedFilter=severity%3E%3DINFO%0Alabels.__uuid__%3D%2229daa1e8-d0cc-4d5a-b0a4-b0538b80ed38%22%0Alabels.__suite__%3D%22c4d130e2-5617-432c-adee-0ff630ccee31%22&authuser=0&expandAll=false&project=kubeadm-167321

### CODE REVIEW

File: lib/xlog/shorten.go [hunk 1]
```diff
@@ -58,6 +59,10 @@ func (c GCLClient) Shorten(ctx context.Context, url string) (short string, err e
 		return "", trace.Wrap(err, "reading response from URL shortener")
 	}
 
+	if resp.StatusCode != 200 {
+		return "", trace.Wrap(fmt.Errorf("%v returned: %v, body: %q", shortenerEndpoint, resp.Status, data))
```
Comment (a-palchikov) [inline lib/xlog/shorten.go:63]: Is this just so we have error logs in the test?
nit: `trace.Errorf` would have the same effect w/o the need to use an intermediary (`fmt.Errorf`)

File: infra/gravity/testsuite.go [hunk 2]
```diff
@@ -179,10 +179,9 @@ func (s *testSuite) getLogLink(testUID string) (string, error) {
 			"expandAll": []string{"false"},
 			"authuser":  []string{"1"},
 			"advancedFilter": []string{
-				fmt.Sprintf(`resource.type="project"
+				fmt.Sprintf(`severity>=INFO
 labels.__uuid__="%s"
-labels.__suite__="%s"
```
Comment (a-palchikov) [inline infra/gravity/testsuite.go:184]: Can you elaborate a bit - does this still work when this is not run from a GCP node?

File: lib/xlog/shorten.go (hunk 1 above)
Comment (wadells) [reply lib/xlog/shorten.go]: fmt.Errorf cleaned up in 893bf8b.

> Is this just so we have error logs in the test?

Yes. These tests aren't run by `make test` (they're nondeterministic integration tests that require cloud auth) and the shortening of code seems dead.  The difference is illustrated here:

```
walt@gcp:~/git/robotest$ go test -count 1 ./lib/xlog/                                                                                                                                   [141]

level=error msg="structured error test" errorf="there was an error <nil>" multi_wrap="<nil>" where="[/lib/xlog/all_test.go:44]" wrapped_no_message="<nil>" wrapped_with_message="<nil>"
--- FAIL: TestShorten (0.19s)
    all_test.go:66: unable to shorten url: https://www.googleapis.com/urlshortener/v1/url returned: 404 Not Found, body: "Not Found"
FAIL
FAIL    github.com/gravitational/robotest/lib/xlog      0.697s
FAIL
walt@gcp:~/git/robotest$ git checkout 05bccb91d26df554f71de25f739bb11df88de3c8     
walt@gcp:~/git/robotest$ go test -count 1 ./lib/xlog/                         

level=error msg="structured error test" errorf="there was an error <nil>" multi_wrap="<nil>" where="[/lib/xlog/all_test.go:44]" wrapped_no_message="<nil>" wrapped_with_message="<nil>"
--- FAIL: TestShorten (0.17s)
    all_test.go:66: unable to shorten url: Decoding response "Not Found"
                invalid character 'N' looking for beginning of value
FAIL
FAIL    github.com/gravitational/robotest/lib/xlog      0.664s
FAIL
```

I'd remove/fix all the shorten stuff, but that was orthogonal to the goal of this PR, and not a priority at this moment.

File: infra/gravity/testsuite.go (hunk 2 above)
Comment (wadells) [reply infra/gravity/testsuite.go:184]: > does this still work when this is not run from a GCP node?

Yes it does. `labels.__suite__` and `labels.__uuid__` are sufficient unique (and indexed) fields to uniquely identify all logs from a robotest run.  We could add another label or a `logName` if we're concerned that something else may sink logs that collide (unlikely given a two UUIDs).

The difference is robotest was filtering on `resource.type="project"`.  However, when run from a gce node, `resource.type="gce_instance"`.  I haven't found a way to turn that off -- it seems to be metadata added on the receiving side instead of the logging client configuration.

There are example metadata in https://github.com/gravitational/robotest/issues/265.

Comment (a-palchikov) [reply infra/gravity/testsuite.go:184]: Ah, I think I misinterpreted the changeset (it appeared to me initially as if you were removing the `__suite__` attribute).

**Review by a-palchikov — APPROVED** [review]
